version: '3.1'

services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_portfolio
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web-app:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.web-app
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "dev"
    depends_on:
      - db

  nginx:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
