FROM python:3.12-slim
WORKDIR app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn
COPY . /app
EXPOSE 5000
CMD if [ "$FLASK_ENV" = 'dev' ] ; then flask run --host 0.0.0.0 -p 5000; else gunicorn -b 0.0.0.0:5000 myflaskapp:app ; fi