# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python checks

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - feature/**
      - hotfix/**

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Mypy
        run: |
          mypy --config-file=.github/workflows/mypy.ini $(git ls-files '*.py' ':!:tests/')
      - name: Lint with pylint
        run: |
          pylint --fail-under=8 --rcfile=.github/workflows/pylint.pylintrc $(git ls-files '*.py' ':!:tests/')
